/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DetectImages.java
 *
 * Created on 29/01/2010, 09:42:57 م
 */
package compare;

import java.awt.FileDialog;
import java.util.StringTokenizer;
import javax.swing.JFileChooser;

/**
 *
 * @author eng
 */
public class DetectImages extends javax.swing.JFrame {

    JFileChooser fc;

    /** Creates new form DetectImages */
    public DetectImages() {
        initComponents();
    }

    public String GetFile() {
        String ret = null;
        try {
            FileDialog fd = new FileDialog(this, "Open File", FileDialog.LOAD);
            fd.setDirectory("/movies");
            fd.show();
            if (fd.getFile() != null) {
                ret = fd.getDirectory() + fd.getFile();                
            }
            return ret;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstImage = new javax.swing.JButton();
        secondImage = new javax.swing.JButton();
        image1Field = new javax.swing.JTextField();
        image2Field = new javax.swing.JTextField();
        start = new javax.swing.JButton();

        setTitle("Compare Images");
        setResizable(false);
        getContentPane().setLayout(null);

        firstImage.setText("Browse 1st image");
        firstImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstImageActionPerformed(evt);
            }
        });
        getContentPane().add(firstImage);
        firstImage.setBounds(0, 13, 140, 30);

        secondImage.setText("Browse 2nd image");
        secondImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondImageActionPerformed(evt);
            }
        });
        getContentPane().add(secondImage);
        secondImage.setBounds(0, 50, 140, 30);
        getContentPane().add(image1Field);
        image1Field.setBounds(150, 20, 280, 20);
        getContentPane().add(image2Field);
        image2Field.setBounds(150, 50, 280, 20);

        start.setText("Start Comparing");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start);
        start.setBounds(220, 80, 140, 30);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-449)/2, (screenSize.height-148)/2, 449, 148);
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        try {
            String image1 = image1Field.getText();
            String image2 = image2Field.getText();
            StringTokenizer divide1 = new StringTokenizer(image1, "\\");
            while (divide1.hasMoreTokens()) {
                image1 = divide1.nextToken();
            }
            StringTokenizer divide2 = new StringTokenizer(image2, "\\");
            while (divide2.hasMoreTokens()) {
                image2 = divide2.nextToken();
            }
            StartComparing s = new StartComparing();
            System.out.println("images name :" + image1 + "-" + image2);
            String args[] = {image1, image2};
            s.main(args);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_startActionPerformed

    private void firstImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstImageActionPerformed
        // TODO add your handling code here:
        try {
            String img1Path = GetFile();
            if (img1Path != null) {
                image1Field.setText(img1Path);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_firstImageActionPerformed

    private void secondImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondImageActionPerformed
        // TODO add your handling code here:
        try {
            String img2Path = GetFile();
            if (img2Path != null) {
                image2Field.setText(img2Path);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_secondImageActionPerformed
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

    public void run() {
    new DetectImages().setVisible(true);
    }
    });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton firstImage;
    private javax.swing.JTextField image1Field;
    private javax.swing.JTextField image2Field;
    private javax.swing.JButton secondImage;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
